name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Elm build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Elm
        uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Build
        run: elm make src/Main.elm --output=dist/main.js
      - name: Deploy
        if: success()
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
