name: CI

on: [push]

jobs:
  build:
    name: Elm build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Elm
        uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1
      - name: Build
        run: elm make src/Main.elm --output=dist/main.js
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
